apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
  labels:
    app: svc-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
        - name: svc-a
          image: dakshsawhneyy/demo-service-a:v
          imagePullPolicy: Always
          ports:
            - containerPort: 9000